[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']

[phases.install]
cmds = [
  'npm install'
]

[phases.build]
cmds = [
  'npm run build -w packages/client',
  'npm run build -w packages/server'
]

[start]
cmd = 'cd packages/server && npx prisma db push --accept-data-loss && node dist/index.js'

